version: '3.9'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=batyr
      - POSTGRES_DB=batyr
      - POSTGRES_DATABASE=batyr
      - POSTGRES_PASSWORD=123qweasd
    volumes:
      - ./pkg:/docker-entrypoint-initdb.d
  cache:
    image: redis
    restart: always
    command: redis-server --appendonly yes
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8888"
    depends_on:
      - database
      - cache
    restart: always
    environment:
      - LISTEN_ADDR=0.0.0.0:8888
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=batyr
      - DB_PASSWORD=123qweasd
      - DB_DATABASE=batyr
      - REDIS_HOST=cache
      - REDIS_PORT=6379
